apiVersion: v1
kind: Secret
data:
  passwd: bGluZWE=
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: remote-mysql
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/matias/kubedata/external/demo_mysql

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: remote-mysql
  namespace: default
spec: 
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: remote-mysql

---
apiVersion: v1
kind: Service
metadata:
  name: remote-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: passwd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: remote-mysql

