apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    app: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: mgckind/demo-app-pie:1.1
        imagePullPolicy: IfNotPresent
        name: demo-app
        env:
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: passwd
        - name: MYSQL_USER
          value: "root" ## <---- 
        - name: MYSQL_SERVER
          value: "remote-mysql"
        - name: MYSQL_PORT
          value: "3306" 
        ports:
        - containerPort: 8081
          name: demo-app
